### ISSUE TITLE
Freigabe für Contao 3.5

### ISSUE THREAD

**Issue by BugBuster1701** [cliffparnitzky/BackendLogs#1]
Kannst du das bitte  für Contao 3.5 freigeben? (composer.json)

**Comment by cliffparnitzky** [comment]
@BugBuster1701 Ist das schon getestet?

**Comment by cliffparnitzky** [comment]
@BugBuster1701 Bitte mal via Composer die Version [dev-support/contao3.5](https://packagist.org/packages/cliffparnitzky/backend-logs#dev-support/contao3.5) installieren und prüfen ob alles geht.

**Comment by BugBuster1701** [comment]
Manuell grad getestet, ok, dann teste ich  noch mal per composer.

**Comment by BugBuster1701** [comment]
Funktioniert bei mir.

**Comment by BugBuster1701** [comment]
"Additional configuration" gehen auch, gerade für error.log.1 was definiert.

**Comment by cliffparnitzky** [comment]
Closed with b13b850

Danke an @BugBuster1701 für Testen.

**Comment by cliffparnitzky** [comment]
Steht mit Version [1.0.1](https://packagist.org/packages/cliffparnitzky/backend-logs#1.0.1) zur Verfügung
